% amat_hitrate_model.m
% ----------------------
% CPEN 315/733 - Project 7: Cache Politics - Group 2, Topic 7
%
% Analytical AMAT sensitivity model:
%     AMAT = hit_time + miss_rate * miss_penalty
%
% Loads the measured results produced by python/analyze_cache_results.py
% (results/experiment_matrix.csv) and:
%   1. Recomputes AMAT analytically from the measured hit rate and the
%      assigned hit_time/miss_penalty pair, as a validation cross-check
%      against the simulator's own reported AMAT (should match, since
%      both use the same formula -- this is the "sanity" cross-check).
%   2. Sweeps miss_rate over [0,1] and plots the analytical AMAT curve
%      with the measured (policy, trace_type) points overlaid, so the
%      report can show how close each policy's operating point is to
%      the theoretical curve at each cache size.
%
% Usage (from the matlab/ directory, with results/experiment_matrix.csv
% already generated by analyze_cache_results.py):
%     >> amat_hitrate_model

function amat_hitrate_model()
    hit_time     = 1.0;   % cycles -- must match --hit-time used in cache_sim
    miss_penalty = 100.0; % cycles -- must match --miss-penalty used in cache_sim

    csv_path = fullfile('..', 'results', 'experiment_matrix.csv');
    if ~isfile(csv_path)
        error(['Cannot find %s.\nRun python/analyze_cache_results.py first ' ...
               'to generate the experiment matrix.'], csv_path);
    end
    T = readtable(csv_path);

    % --- Validation cross-check: analytical AMAT vs. simulator-reported AMAT ---
    analytical_amat = hit_time + (1 - T.hit_rate) * miss_penalty;
    residual = abs(analytical_amat - T.amat);
    tol = 0.05; % cycles
    fprintf('Validation: max |analytical AMAT - simulator AMAT| = %.6f cycles\n', max(residual));
    if max(residual) > tol
        warning('Analytical/measured AMAT mismatch exceeds tolerance (%.2f cycles).', tol);
    else
        fprintf('PASS: analytical model matches simulator output within %.2f cycles.\n', tol);
    end

    % --- Sensitivity curve: AMAT vs. miss rate, with measured points overlaid ---
    miss_rate_sweep = linspace(0, 1, 200);
    amat_sweep = hit_time + miss_rate_sweep * miss_penalty;

    figure('Name', 'AMAT sensitivity model', 'Color', 'w');
    plot(miss_rate_sweep, amat_sweep, 'k-', 'LineWidth', 1.5, ...
         'DisplayName', sprintf('Analytical: AMAT = %.1f + missRate x %.0f', hit_time, miss_penalty));
    hold on;

    policies = unique(T.policy);
    colours = lines(numel(policies));
    markers = {'o', 's', '^', 'd', 'p'};
    for i = 1:numel(policies)
        mask = strcmp(T.policy, policies{i});
        scatter(1 - T.hit_rate(mask), T.amat(mask), 60, colours(i, :), ...
                markers{mod(i - 1, numel(markers)) + 1}, 'filled', ...
                'DisplayName', policies{i});
    end
    xlabel('Miss rate');
    ylabel('AMAT (cycles)');
    title('AMAT vs. miss rate: analytical model vs. measured (policy, trace, size) points');
    legend('Location', 'northwest');
    grid on;
    hold off;

    out_png = fullfile('..', 'results', 'amat_sensitivity_model.png');
    saveas(gcf, out_png);
    fprintf('Saved %s\n', out_png);
end
